CREATE DATABASE bd_registro;
use mysql;


CREATE USER 'OPENSHIFT_MYSQL_DB_USERNAME'@'OPENSHIFT_MYSQL_DB_HOST' IDENTIFIED BY 'OPENSHIFT_MYSQL_DB_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON bd_registro.* TO 'OPENSHIFT_MYSQL_DB_USERNAME'@'OPENSHIFT_MYSQL_DB_HOST';